# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    campaignchain.location.twitter.status:
        bundle_name: "campaignchain/location-twitter"
        module_identifier: "campaignchain-twitter-status"

services:
    campaignchain.location.twitter_user:
        class: CampaignChain\Location\TwitterBundle\EntityService\TwitterUserService
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.job.report.location.twitter:
        class: CampaignChain\Location\TwitterBundle\Job\ReportTwitterUserMetrics
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
